// AUTO-GENERATED by scripts/generate-helpers-source.js. Do not edit.
// Source: src/lib/helpers/default-helpers.js
/* eslint-disable */
export const DEFAULT_HELPERS_RAW = `
/*
 * Default helpers available to every \`generate()\` in a mock step.
 *
 * Authoring rules:
 *   1. Prefer \`function\` declarations — they hoist, so cross-helper calls
 *      work regardless of order.
 *   2. No \`require\` / \`import\` inside function bodies. The VM sandbox has no
 *      module system. Only sandbox-whitelisted globals (Math, Date, JSON, …)
 *      and sibling helpers are in scope.
 *   3. If the helper needs request-scope data, take \`sessionData\` as an
 *      explicit parameter. Free-variable references to \`sessionData\` do NOT
 *      resolve at runtime — helpers run at script scope, \`sessionData\` is
 *      only a parameter of \`generate()\`.
 *   4. Document every helper with a leading JSDoc block (\`@param\`, \`@returns\`).
 *
 * The full file (minus the trailing \`module.exports = {...}\` block) is
 * embedded verbatim into the sandbox bundle by
 * \`scripts/generate-helpers-source.js\`, so JSDoc reaches end users unchanged.
 * Re-run \`npm run helpers:gen\` after editing.
 */

/**
 * Resolve the BPP or BAP subscriber URL from session data.
 *
 * @param {Object} sessionData  session data (reads \`bppUri\` or \`bapUri\`)
 * @param {"bpp"|"bap"|string} type  subscriber kind; anything other than "bpp" returns bapUri
 * @returns {string} the subscriber URL
 */
function getSubscriberUrl(sessionData, type) {
	if (type === "bpp") {
		return sessionData.bppUri;
	} else {
		return sessionData.bapUri;
	}
}

/**
 * Generate a UUID v4 (RFC 4122, random-based).
 *
 * @returns {string} a new UUID v4, e.g. "550e8400-e29b-41d4-a716-446655440000"
 */
function uuidv4() {
	return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, function (c) {
		const r = (Math.random() * 16) | 0;
		const v = c === "x" ? r : (r & 0x3) | 0x8;
		return v.toString(16);
	});
}

/**
 * Generate a 6-digit numeric string ID in [100000, 999999].
 *
 * @returns {string} a zero-padded 6-digit numeric string
 */
function generate6DigitId() {
	return Math.floor(100000 + Math.random() * 900000).toString();
}

/**
 * Get the current ISO-8601 UTC timestamp.
 *
 * @returns {string} e.g. "2026-04-23T12:34:56.789Z"
 */
function currentTimestamp() {
	return new Date().toISOString();
}

/**
 * Convert an ISO 8601 duration string (e.g. "PT1H30M", "P2DT3H") to total seconds.
 *
 * Approximations used: 1 week = 7 days, 1 month ≈ 30.42 days (2628288 sec),
 * 1 year = 365 days. Not calendar-exact.
 *
 * @param {string} duration  ISO 8601 duration string
 * @returns {number} total seconds; 0 when the input is unparseable
 */
function isoDurToSec(duration) {
	const durRE =
		/P((\\d+)Y)?((\\d+)M)?((\\d+)W)?((\\d+)D)?T?((\\d+)H)?((\\d+)M)?((\\d+)S)?/;
	const s = durRE.exec(duration);
	if (!s) return 0;

	return (
		(Number(s?.[2]) || 0) * 31536000 +
		(Number(s?.[4]) || 0) * 2628288 +
		(Number(s?.[6]) || 0) * 604800 +
		(Number(s?.[8]) || 0) * 86400 +
		(Number(s?.[10]) || 0) * 3600 +
		(Number(s?.[12]) || 0) * 60 +
		(Number(s?.[14]) || 0)
	);
}

/**
 * Mutate \`payload.context\` in place to set the city code from \`inputs.city_code\`.
 *
 * Version-aware: ONDC v1.x uses flat \`context.city\`, v2.x uses nested
 * \`context.location.city.code\`. Falls back to "*" when \`city_code\` is missing.
 * No-op when \`inputs\` is falsy.
 *
 * @param {Object} payload  payload with a \`context\` to mutate
 * @param {Object|null|undefined} inputs  object with optional \`city_code\`
 * @returns {string|undefined} "*" when inputs is falsy; otherwise undefined
 */
function setCityFromInputs(payload, inputs) {
	if (!inputs) return "*";
	const version =
		payload.context.version || payload.context.core_version || "2.0.0";
	if (version.startsWith("1")) {
		payload.context.city = inputs.city_code ?? "*";
	} else {
		payload.context.location.city.code = inputs.city_code ?? "*";
	}
}

/**
 * Build a form submission URL from session data.
 *
 * @param {string} domain       ONDC domain (e.g. "ONDC:RET10")
 * @param {string} formId       form identifier
 * @param {Object} sessionData  reads \`mockBaseUrl\`, \`transactionId[0]\`, \`sessionId\`
 * @returns {string} \`\${baseURL}/forms/\${domain}/\${formId}/?transaction_id=...&session_id=...\`
 */
function createFormURL(domain, formId, sessionData) {
	const baseURL = sessionData.mockBaseUrl;
	const transactionId = sessionData.transactionId[0];
	const sessionId = sessionData.sessionId;
	return \`\${baseURL}/forms/\${domain}/\${formId}/?transaction_id=\${transactionId}&session_id=\${sessionId}\`;
}

/**
 * Generate a consent handler from the Finvu AA Service.
 *
 * Reads the service base URL from \`sessionData.finvuUrl\` — the installing
 * service MUST include that origin in
 *   MockRunner.initSharedRunner({ allowedFetchBaseUrls: [...] })
 * otherwise the sandboxed fetch will be blocked.
 *
 * Times out after 10s via AbortController.
 *
 * @param {Object} sessionData  session data; \`sessionData.finvuUrl\` is required
 * @param {Object} params
 * @param {string} params.custId                customer ID (required)
 * @param {string} [params.templateName]        defaults to "FINVUDEMO_TESTING"
 * @param {string} [params.consentDescription]  defaults to "Gold Loan Account Aggregator Consent"
 * @param {string} [params.redirectUrl]         defaults to "https://google.co.in"
 * @returns {Promise<string>} the \`consentHandler\` returned by the AA service
 * @throws {Error} when \`custId\` or \`sessionData.finvuUrl\` is missing, on non-OK
 *   response, on missing \`consentHandler\` in the body, or on 10s timeout
 */
async function generateConsentHandler(
	sessionData,
	{
		custId,
		templateName = "FINVUDEMO_TESTING",
		consentDescription = "Gold Loan Account Aggregator Consent",
		redirectUrl = "https://google.co.in",
	},
) {
	if (!custId) {
		throw new Error("custId is required");
	}
	const baseUrl = sessionData && sessionData.finvuUrl;
	if (!baseUrl) {
		throw new Error("sessionData.finvuUrl is required");
	}

	const url = \`\${baseUrl}/finvu-aa/consent/generate\`;

	const payload = {
		custId,
		templateName,
		consentDescription,
		redirectUrl,
	};

	console.log("Calling Finvu AA Service:", url);
	console.log("Consent request payload:", payload);

	const controller = new AbortController();
	const timeout = setTimeout(() => controller.abort(), 10000);

	try {
		const res = await fetch(url, {
			method: "POST",
			headers: {
				"Content-Type": "application/json",
			},
			body: JSON.stringify(payload),
			signal: controller.signal,
		});

		if (!res.ok) {
			const text = await res.text();
			throw new Error(\`Request failed: \${res.status} \${text}\`);
		}

		const data = await res.json();

		if (!data || !data.consentHandler) {
			throw new Error("Invalid response: consentHandler missing");
		}

		return data.consentHandler;
	} catch (err) {
		if (err && err.name === "AbortError") {
			throw new Error("Request timed out after 10 seconds");
		}
		throw err;
	} finally {
		clearTimeout(timeout);
	}
}
`;
